ProjectLigaNosWeb/Controllers/ClubsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectLigaNosWeb.Data;
using ProjectLigaNosWeb.Helpers;
using ProjectLigaNosWeb.Models;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectLigaNosWeb.Controllers
{
    [Authorize(Roles = "Admin, Clube")]
    public class ClubsController : Controller
    {
        private readonly IClubsRepository _clubesRepository;
        private readonly DataContext _context;
        private readonly IStatisticsRepository _statisticsRepository;
        private readonly IUserHelper _userHelper;
        private readonly IBlobHelper _blobHelper;
        private readonly IConverterHelper _converterHelper;

        public ClubsController(IClubsRepository clubesRepository, IStatisticsRepository statisticsRepository, IUserHelper userHelper, IBlobHelper blobHelper, IConverterHelper converterHelper , DataContext context)
        {
            _clubesRepository = clubesRepository;
            _statisticsRepository = statisticsRepository;
            _userHelper = userHelper;
            _blobHelper = blobHelper;
            _converterHelper = converterHelper;
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_clubesRepository.GetAll().OrderBy(c => c.Name));
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClubNotFound");
            }

            var clubes = await _clubesRepository.GetByIdAsync(id.Value);
            if (clubes == null)
            {
                return new NotFoundViewResult("ClubNotFound");
            }

            return View(clubes);
        }

        // GET: Clubes/Create
        [Authorize(Roles = "Admin, Clube")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clubes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(ClubViewModel model)
        {
            if (ModelState.IsValid)
            {
                bool clubExists = await _clubesRepository
                    .GetAll()
                    .AnyAsync(c => c.Name == model.Name || c.Acroyn == model.Acroyn);

                if (clubExists)
                {
                    ModelState.AddModelError(string.Empty, "A club with the same name or abbreviation already exists.");
                    return View(model); 
                }

                Guid imageId = Guid.Empty;

                if (model.ImageFile != null && model.ImageFile.Length > 0)
                {
                    imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "clubs");
                }

                var clubes = _converterHelper.ToClubs(model, imageId, true);
                clubes.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);

                await _clubesRepository.CreateAsync(clubes);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }


        // GET: Clubes/Edit/5
        [Authorize(Roles = "Admin, Clube")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClubNotFound");
            }

            var clubes = await _clubesRepository.GetByIdAsync(id.Value);
            if (clubes == null)
            {
                return new NotFoundViewResult("ClubNotFound");
            }

            var model = _converterHelper.ToClubeViewModel(clubes);

            return View(model);
        }


        // POST: Clubes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ClubViewModel model)
        {
            if (id != model.Id)
            {
                return new NotFoundViewResult("ClubNotFound");
            }

            if (ModelState.IsValid)
            {
                var club = await _clubesRepository.GetByIdAsync(id);
                if (club == null)
                {
                    return new NotFoundViewResult("ClubNotFound");
                }

                club.Name = model.Name;
                club.Acroyn = model.Acroyn;
                club.DateFund = model.DateFund;
                club.City = model.City;
                club.Country = model.Country;
                club.CapacityStadium = model.CapacityStadium;
                club.President = model.President;
                club.NationalTitles = model.NationalTitles;
                club.InternationalTitles = model.InternationalTitles;

                if (model.ImageFile != null && model.ImageFile.Length > 0)
                {
                    club.ImageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "clubs");
                }

                await _clubesRepository.UpdateAsync(club);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: Clubes/Delete/5
        [Authorize(Roles = "Admin, Clube")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var club = await _clubesRepository.GetByIdAsync(id.Value);
            if (club == null)
            {
                return NotFound();
            }

            var hasPlayers = await _context.Players.AnyAsync(p => p.ClubId == club.Id);

            if (hasPlayers)
            {
                var players = await _context.Players.Where(p => p.ClubId == club.Id).ToListAsync();
                _context.Players.RemoveRange(players);

            
            }

            await _clubesRepository.DeleteAsync(club);

            return RedirectToAction(nameof(Index));
        }

        // POST: Clubs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var club = await _clubesRepository.GetByIdAsync(id);

            if (club == null)
            {
                return NotFound();
            }

            var hasPlayers = await _context.Players.AnyAsync(p => p.ClubId == club.Id);

            if (hasPlayers)
            {

                var players = await _context.Players.Where(p => p.ClubId == club.Id).ToListAsync();
                _context.Players.RemoveRange(players);

              
            }

            await _clubesRepository.DeleteAsync(club);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult ClubNotFound()
        {
            return View();
        }
    }
}

ProjectLigaNosWeb/Controllers/GamesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectLigaNosWeb.Data;
using ProjectLigaNosWeb.Data.Entities;
using ProjectLigaNosWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectLigaNosWeb.Controllers
{
    [Authorize(Roles = "Admin, Funcionario")]
    public class GamesController : Controller
    {
        private readonly IGamesRepository _gamesRepository;
        private readonly IClubsRepository _clubsRepository;
        private readonly DataContext _context;
        private readonly IStatisticsRepository _statisticsRepository;

        public GamesController(IGamesRepository gamesRepository, IClubsRepository clubsRepository,  DataContext context, IStatisticsRepository statisticsRepository)
        {
            _gamesRepository = gamesRepository;
            _clubsRepository = clubsRepository;
            _context = context;
            _statisticsRepository = statisticsRepository;
        }
        public async Task<IActionResult> Index()
        {
            var games = await _gamesRepository.GetAllAsync();
            if (games == null || !games.Any())
            {
                ModelState.AddModelError("", "No game found.");
                return View(new List<Games>()); 
            }

            return View(games);
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogo = await _gamesRepository.GetAllAsync()
                .ContinueWith(t => t.Result.FirstOrDefault(g => g.Id == id.Value));

            if (jogo == null)
            {
                return NotFound();
            }

            await _context.Entry(jogo)
                .Reference(g => g.ClubHome) 
                .LoadAsync();
            await _context.Entry(jogo)
                .Reference(g => g.ClubAway) 
                .LoadAsync();

            return View(jogo);
        }


        // GET: Jogos/Create
        public async Task<IActionResult> Create()
        {
            var clubs = await _clubsRepository.GetAllAsync();
            var model = new GameViewModel
            {
                ClubsHome = clubs.Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList(),
                ClubsAway = clubs.Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList()
            };

            return View(model);
        }

        // POST: Jogos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Funcionario,Admin")]
        public async Task<IActionResult> Create(GameViewModel model)
        {
            if (ModelState.IsValid)
            {
                var existingGame = await _gamesRepository.GetAllAsync();
                var gameOnSameDay = existingGame.FirstOrDefault(g =>
                    g.Data == model.Data &&
                    ((g.ClubHomeId == model.ClubHomeId && g.ClubAwayId == model.ClubAwayId) ||
                    (g.ClubHomeId == model.ClubAwayId && g.ClubAwayId == model.ClubHomeId))); 

                if (gameOnSameDay != null)
                {
                    ModelState.AddModelError("", "A game between these teams already exists on the same day.");

                    var clubs = await _clubsRepository.GetAllAsync();
                    model.ClubsHome = clubs.Select(c => new SelectListItem
                    {
                        Value = c.Id.ToString(),
                        Text = c.Name
                    }).ToList();
                    model.ClubsAway = clubs.Select(c => new SelectListItem
                    {
                        Value = c.Id.ToString(),
                        Text = c.Name
                    }).ToList();

                    return View(model);
                }

                var game = new Games
                {
                    Name = model.Name,
                    Data = model.Data,
                    ClubHomeId = model.ClubHomeId,
                    ClubAwayId = model.ClubAwayId,
                    HomeGoals = model.HomeGoals,
                    AwayGoals = model.AwayGoals,
                    Localizacao = model.Localizacao
                };

                await _gamesRepository.CreateAsync(game);

                if (game.Id == 0) 
                {
                    ModelState.AddModelError("", "The game was not saved correctly.");
                    return View(model);
                }

                await UpdateStatistics(game); 

                return RedirectToAction(nameof(Index));
            }

            var clubsFallback = await _clubsRepository.GetAllAsync();
            model.ClubsHome = clubsFallback.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();
            model.ClubsAway = clubsFallback.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();

            return View(model);
        }


        private async Task UpdateStatistics(Games game)
        {
            var homeStat = await _statisticsRepository.GetAllAsync()
                .ContinueWith(t => t.Result.FirstOrDefault(s => s.ClubId == game.ClubHomeId));

            if (homeStat == null)
            {
                homeStat = new Statistics
                {
                    ClubId = game.ClubHomeId,
                    MatchesPlayed = 1,
                    GoalsScored = game.HomeGoals,
                    GoalsConceded = game.AwayGoals,
                    HomeWins = game.HomeGoals > game.AwayGoals ? 1 : 0,
                    AwayWins = 0,
                    OverallRanking = game.HomeGoals > game.AwayGoals ? 3 : (game.HomeGoals == game.AwayGoals ? 1 : 0), 
                    GameId = game.Id
                };
                await _statisticsRepository.AddAsync(homeStat);
            }
            else
            {
                homeStat.MatchesPlayed++;
                homeStat.GoalsScored += game.HomeGoals;
                homeStat.GoalsConceded += game.AwayGoals;

                if (game.HomeGoals > game.AwayGoals)
                {
                    homeStat.HomeWins++;
                    homeStat.OverallRanking += 3; 
                }
                else if (game.HomeGoals == game.AwayGoals)
                {
                    homeStat.OverallRanking += 1; 
                }

                await _statisticsRepository.UpdateAsync(homeStat);
            }

            var awayStat = await _statisticsRepository.GetAllAsync()
                .ContinueWith(t => t.Result.FirstOrDefault(s => s.ClubId == game.ClubAwayId));

            if (awayStat == null)
            {
                awayStat = new Statistics
                {
                    ClubId = game.ClubAwayId,
                    MatchesPlayed = 1,
                    GoalsScored = game.AwayGoals,
                    GoalsConceded = game.HomeGoals,
                    HomeWins = 0,
                    AwayWins = game.AwayGoals > game.HomeGoals ? 1 : 0,
                    OverallRanking = game.AwayGoals > game.HomeGoals ? 3 : (game.AwayGoals == game.HomeGoals ? 1 : 0), 
                    GameId = game.Id
                };
                await _statisticsRepository.AddAsync(awayStat);
            }
            else
            {
                awayStat.MatchesPlayed++;
                awayStat.GoalsScored += game.AwayGoals;
                awayStat.GoalsConceded += game.HomeGoals;

                if (game.AwayGoals > game.HomeGoals)
                {
                    awayStat.AwayWins++;
                    awayStat.OverallRanking += 3;
                }
                else if (game.AwayGoals == game.HomeGoals)
                {
                    awayStat.OverallRanking += 1;
                }

                await _statisticsRepository.UpdateAsync(awayStat);
            }
        }

        // GET: Jogos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogos = await _gamesRepository.GetByIdAsync(id.Value);
            if (jogos == null)
            {
                return NotFound();
            }

            var allClubs = await _clubsRepository.GetAllAsync();
            if (allClubs == null || !allClubs.Any())
            {
                ModelState.AddModelError("", "No club found.");
                return View(jogos);
            }

            ViewBag.ClubsHome = allClubs.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();

            ViewBag.ClubsAway = allClubs.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();

            return View(jogos);
        }




        // POST: Jogos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Games jogos)
        {
            if (id != jogos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)

ProjectLigaNosWeb/Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ProjectLigaNosWeb.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
    }
}

ProjectLigaNosWeb/Views/Shared/_Layout.cshtml
@using System.IO;
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment WebHostEnvironment

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectLigaNosWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Raleway:500,800" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.syncfusion.com/ej2/20.3.0.47/material.css" rel="stylesheet" />


    <link rel="stylesheet" href="~/css/site.css" />


    <style>
        body {
            background-color: #e9ecef;
        }

        .navbar {
            transition: background-color 0.5s ease;
        }

            .navbar:hover {
                background-color: #f8f9fa;
            }

        .nav-link {
            position: relative;
            transition: color 0.3s ease;
            padding-bottom: 5px;
            font-weight: 500; 
        }

            .nav-link::after {
                content: '';
                display: block;
                width: 0;
                height: 2px;
                background: #ff4500; 
                transition: width 0.3s ease, background-color 0.3s ease;
                position: absolute;
                left: 50%;
                bottom: 0;
            }

            .nav-link:hover::after,
            .nav-link:focus::after {
                width: 100%;
                left: 0;
            }

            .nav-link:not(:hover)::after,
            .nav-link:not(:focus)::after {
                width: 0;
            }

        .navbar-nav .dropdown-toggle {
            color: #000;
            font-weight: 500; 
        }

            .navbar-nav .dropdown-toggle::after {
                display: none; 
            }

        .navbar-nav .dropdown:hover .dropdown-toggle::after {
            transform: none; 
        }

        .navbar-nav .dropdown-item {
            color: #000;
            font-weight: 500; 
        }

            .navbar-nav .dropdown-item:hover {
                background-color: #f8f9fa; 
            }

        .footer {
            background-color: #f8f9fa;
            padding: 10px 0;
        }
    </style>

    <script src="https://cdn.syncfusion.com/ej2/20.3.0.47/dist/ej2.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetoFinalWebLigaNos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fa-solid fa-house-user"></i> Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clubs" asp-action="Index">
                                <i class="fa-solid fa-futbol"></i> Clubs
                            </a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa-solid fa-user-tie"></i>Admin</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="">Users</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="">Roles</a></li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">
                                <i class="fa-solid fa-person"></i>Players
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">
                                <i class="fa-solid fa-users"></i>Games
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="Index">
                                <i class="fa-solid fa-ranking-star"></i> Statistics
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">
                                <i class="fa-solid fa-lock"></i> Privacy
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="ChangeUser">
                                    @{
                                        var profilePicturePath = "~/images/users/" + User.Identity.Name + ".png";
                                        var filePath = System.IO.Path.Combine(WebHostEnvironment.WebRootPath, "images/users", User.Identity.Name + ".png");

                                        if (!System.IO.File.Exists(filePath))
                                        {
                                            profilePicturePath = "~/images/users/default.png";
                                        }
                                        else
                                        {
                                            profilePicturePath += "?t=" + DateTime.Now.Ticks;
                                        }

                                        profilePicturePath = Url.Content(profilePicturePath);
                                    }
                                    <img src="@profilePicturePath" alt="Profile Picture"
                                         style="width: 30px; height: 30px; border-radius: 50%; margin-right: 5px;" />
                                    @this.User.Identity.Name
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">
                                    <i class="fa-solid fa-right-from-bracket"></i>Logout
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">
                                    <i class="fa-solid fa-door-open"></i>Login
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProjectLigaNosWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>

            <div class="social-icons">
                <a href="https://www.facebook.com/profile.php?id=100006994865135&locale=pt_PT" target="_blank" class="text-dark">
                    <i class="fa-brands fa-facebook"></i> Facebook
                </a>
                <a href="https://www.instagram.com/davidmjg10/" target="_blank" class="text-dark">
                    <i class="fa-brands fa-instagram"></i> Instagram
                </a>
                <a href="https://www.linkedin.com/in/david-gon%C3%A7alves-3a12362ab/" target="_blank" class="text-dark">
                    <i class="fa-brands fa-linkedin"></i> LinkedIn
                </a>
            </div>
        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>